apiVersion: v1
kind: Service
metadata: #meta data seria a especificação do meu pod
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:  
    - port: 80
      #targetPor: 80 #Porta de comunicação do clust
      nodePort: 30000 #Porta de saida do nosso portal
  selector:
    app: portal-noticias
