apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80 #vai ouvir na porta 80
      nodePort: 30002 #sera utilizado para acesso externo!!
  selector:    
    app: sistema-noticias #gerenciamento pela label de sistema-noticia